# Package Overview
package_name: disaster_response

# Data Files
messages_file_name: disaster_messages.csv
categories_file_name: disaster_categories.csv
database_file_name: DisasterResponse.db

# Model file
model_save_file: ml_pipeline.pkl

# SQL table
table_name: DisasterResponse

# Variables
# Input feature
features: message

# The target variables
targets:
  - related
  - request
  - offer
  - aid_related
  - medical_help
  - medical_products
  - search_and_rescue
  - security
  - military
  - child_alone
  - water 
  - food
  - shelter
  - clothing
  - money
  - missing_people
  - refugees
  - death
  - other_aid
  - infrastructure_related
  - transport
  - buildings
  - electricity
  - tools
  - hospitals
  - shops
  - aid_centers
  - other_infrastructure
  - weather_related
  - floods
  - storm
  - fire
  - earthquake
  - cold
  - other_weather
  - direct_report